name: bitcoin_ui_kit
description: The Bitcoin UI Kit for Flutter.
version: 1.0.2
homepage: https://github.com/bdgwallet/bitcoinuikit-flutter

environment:
  sdk: ">=2.18.5 <3.0.2"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - icons/
